apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
   name: expense
   region: us-east-1

managedNodeGroups:
  - name: expense
    instance_types:["m5.large", "c3.large","c4.large","c5.large"]
    desriedCapacity: 3
    spot: true    

  